package com.jin12.reviews_api.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

/**
 * Review entity representing a product review.
 * generatedByAI indicates if the review was created by AI or a user.
 */
@Entity
@Data
@Table(name = "reviews")
@NoArgsConstructor
public class Review {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String name;

    @Lob // Use CLOB/TEXT instead of VARCHAR(255) to allow longer review content
    @Column
    private String reviewText;

    @Column(nullable = false)
    private int rating;

    @Column(nullable = false)
    private LocalDate date;

    @Column(nullable = false)
    private boolean generatedByAI;

    @ManyToOne
    @JoinColumn(name = "product_id", nullable = false)
    @JsonIgnore // Prevents circular JSON serialization between Review and Product
    private Product product;

    /**
     * Constructor for creating a new Review instance.
     *
     * @param name         the reviewer’s name
     * @param reviewText   the review content
     * @param rating       the rating (1–5)
     * @param generatedByAI true if the review was generated by AI
     */
    public Review(String name, String reviewText, int rating, boolean generatedByAI) {
        this.name = name;
        this.reviewText = reviewText;
        this.rating = rating;
        this.generatedByAI = generatedByAI;
    }
}